acme_news:
    resource: "@AcmeNewsBundle/Controller/NewsController.php"
    type:     annotation

app:
    resource: "@AcmeNewsBundle/Controller/DefaultController.php"
    prefix:   /
    type:     annotation