acme_news:
    resource: "@AcmeNewsBundle/Controller/NewsController.php"
    type:     annotation

homepage:
    path: /
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    :default:index.html.twig