services:
    app.news_repository:
        class:     AcmeNewsBundle\Repository\NewsRepository
        factory:   ['@doctrine.orm.entity_manager', getRepository]
        arguments: [AcmeNewsBundle\Entity\News]
